# Generated by Django 4.1a1 on 2022-05-18 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_toggle_m2m.toggle


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_recipestep"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date for plan")),
                (
                    "recipes",
                    models.ManyToManyField(related_name="meal_plans", to="core.recipe"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(models.Model, django_toggle_m2m.toggle.ToggleManyToMany),
        ),
        migrations.AddConstraint(
            model_name="mealplan",
            constraint=models.UniqueConstraint(
                fields=("user", "date"), name="unique_user_date"
            ),
        ),
    ]
